syntax =  "proto3";
option java_package = "com.hsj.messagingdemo.dto";

enum MessageType {
  X3DH = 0;
  DIRECT = 1;
  GROUP = 2;
  USER_ADDED =3;
  USER_REMOVED = 4;
  GROUP_INVITE = 5;
  GROUP_MEMBERSHIP = 6;
}

message MessageFile{
  string file_id = 1;
  bytes data = 2;
  string mime_type = 3;
  string file_name = 4;
}

message FileInfo{
  string file_id =1;
   bytes file_iv = 2;
}

message MessageContents{
  optional string text =1;
  optional FileInfo file_info = 2;
  optional UserGroupChange user_group_change =3;
  optional GroupInvite group_invite=4;
  optional GroupMembership group_membership=5;
}

message GroupInvite{
  string group_chat_id = 1;
  string group_chat_name = 2;
  bytes group_key = 3;
  optional FileInfo group_image= 4; 
}

message GroupMembership{
  bytes group_key = 1;
}

// deleting or addition is given by the message type in the header
message UserGroupChange{
  string user_id = 1;
  bytes new_group_key = 2;
}

message MessageHeader{
  MessageType type = 1;
  bytes dh_public_key = 2;
  uint32 chain_length = 3;
  uint32 previous_length = 4;
  bytes message_iv = 5;
  optional string sender_id = 6;
  optional string chat_id = 7;
  optional bytes ephemeral_key = 8;
  optional bytes one_time_prekey = 9;
}

message ChatMessage {
  optional MessageHeader message_header = 1;
  optional bytes message_header_encrypted= 2;
  bytes message_contents_encrypted= 3;
  uint64 timestamp = 4;
  optional bytes header_iv = 5;
}
message PreKeyBundle {
  optional string id = 1;
  bytes identity_key = 2;
  bytes verifier_key = 3;
  bytes signed_prekey = 4;
  bytes prekey_signature = 5; 
  repeated bytes one_time_prekey = 6;
}

message KeyPair {
    bytes public_key = 1;
    bytes private_key = 2;
}

message Identity{
    string user_id = 1;
    KeyPair identity_key = 2;
    KeyPair verifier_key = 3;
    KeyPair signed_prekey = 4;
    uint64 signed_prekey_expiration= 5 ;
    repeated KeyPair one_time_prekey= 6;
}

