spring.application.name=messagingdemo
spring.kafka.bootstrap-servers=localhost:9092
# spring.kafka.consumer.group-id=my-group-id
spring.kafka.producer.properties.spring.json.add.type.headers=false

# WebSocket connection and messaging
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket.messaging=DEBUG

# Show STOMP message routing
logging.level.org.springframework.messaging.simp.broker=DEBUG
logging.level.org.springframework.messaging.simp=DEBUG


spring.data.mongodb.uri=mongodb+srv://localhost:27017/messagingclone
spring.data.mongodb.database=messagingclone

remember-me-key=@*9hhf3h(#hdiwb)